---
title: "comradesOO"
author: Jonathan Price
date: "`r.Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: vignette
vignette: >
  %\VignetteIndexEntry{comradessOO}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# COMRADES experiment


The COMRADES experimental protocol for the prediction of RNA structure in vivo was first published in 2018 (Ziv et al., 2019) where they predicted the structure of the Zika virus. The protocol has subsequently been use to predict the structure of SARS-CoV-2 (Ziv et al., 2020).

To gain a better understanding of the protocol see:


* COMRADES determines in vivo RNA structures and interactions. (2018). Omer Ziv, Marta Gabryelska, Aaron Lun, Luca Gebert. Jessica Sheu-Gruttadauria and Luke Meredith, Zhong-Yu Liu,  Chun Kit Kwok, Cheng-Feng Qin, Ian MacRae, Ian Goodfellow , John Marioni, Grzegorz Kudla, Eric Miska.  Nature Methods. Volume 15. https://doi.org/10.1038/s41592-018-0121-0   

* The Short- and Long-Range RNA-RNA Interactome of SARS-CoV-2. (2020). Omer Ziv, Jonathan Price, Lyudmila Shalamova, Tsveta Kamenova, Ian Goodfellow, Friedemann Weber, Eric A. Miska. Molecular Cell,
Volume 80
    https://doi.org/10.1016/j.molcel.2020.11.004

![Figure from Ziv et al., 2020. Virus-inoculated cells are crosslinked using clickable psoralen. Viral RNA is pulled down from the cell lysate using an array of biotinylated DNA probes, following digestion of the DNA probes and fragmentation of the RNA. Biotin is attached to crosslinked RNA duplexes via click chemistry, enabling pulling down crosslinked RNA using streptavidin beads. Half of the RNA duplexes are proximity-ligated, following reversal of the crosslinking to enable sequencing. The other half serves as a control, in which crosslink reversal proceeds the proximity ligation](comradesProtocol.jpg){width=100%}


* figures of how comrades works
* an explanation of the data

# COMRADES data pre-processing

* The data pre-processing steps (figure)

# comradesOO Package

* figures of what the package does  - clustering - folding 
* links to each of the classes as we go. 
* explanation of the way the analysis is stored 
* methods for producing different analysis and results


# 3 classes

explanation of the 3 classes linked to explanation above 

## comradesDataSet
detailed explanation of the class with slots etc

## comradesClusteredDataSet
detailed explanation of the class with slots etc

## comradesFoldedDataSet
detailed explanation of the class with slots etc

# Standard Workflow

code for a standard workflow. 
